% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name intersect
%  @associatedFile /MATLAB Drive/intersect.m
%  @mostRecentlyActioned true
%  @uniqueId 7B2B0C0A

intersect

%% @name findPriceQuantity
%  @associatedFile /MATLAB Drive/findPriceQuantity.m
%  @mostRecentlyActioned true
%  @uniqueId F5D8E1B1

findPriceQuantity

%% @name meanOreExtraction
%  @associatedFile /MATLAB Drive/meanOreExtraction.m
%  @mostRecentlyActioned true
%  @uniqueId 7CF67C6B

meanOreExtraction

%% @name randomOreExtraction
%  @associatedFile /MATLAB Drive/randomOreExtraction.m
%  @mostRecentlyActioned true
%  @uniqueId F426FBB3

randomOreExtraction

